schema:
  - 'https://graphql.anilist.co'
documents:
  - './src/**/*.graphql'
generates:
  ./src/network/queries/__generated__/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      